[2025-08-07 22:33:44,199] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.run_py_spark_job scheduled__2025-08-07T20:33:04.723597+00:00 [queued]>
[2025-08-07 22:33:44,215] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.run_py_spark_job scheduled__2025-08-07T20:33:04.723597+00:00 [queued]>
[2025-08-07 22:33:44,216] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 22:33:44,216] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-07 22:33:44,216] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 22:33:44,239] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_py_spark_job> on 2025-08-07 20:33:04.723597+00:00
[2025-08-07 22:33:44,247] {standard_task_runner.py:52} INFO - Started process 5082 to run task
[2025-08-07 22:33:44,254] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'run_py_spark_job', 'scheduled__2025-08-07T20:33:04.723597+00:00', '--job-id', '660', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmp3l_8a127', '--error-file', '/tmp/tmpzhrmvxie']
[2025-08-07 22:33:44,256] {standard_task_runner.py:80} INFO - Job 660: Subtask run_py_spark_job
[2025-08-07 22:33:44,357] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.run_py_spark_job scheduled__2025-08-07T20:33:04.723597+00:00 [running]> on host 98bad2c91b1f
[2025-08-07 22:33:44,711] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alla
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=run_py_spark_job
AIRFLOW_CTX_EXECUTION_DATE=2025-08-07T20:33:04.723597+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-07T20:33:04.723597+00:00
[2025-08-07 22:33:44,713] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-07 22:33:44,714] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && spark-submit py_spark/pyspark_streaming_meteo.py']
[2025-08-07 22:33:44,737] {subprocess.py:85} INFO - Output:
[2025-08-07 22:33:44,943] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-08-07 22:33:44,946] {subprocess.py:92} INFO - JAVA_HOME is not set
[2025-08-07 22:33:44,947] {subprocess.py:96} INFO - Command exited with return code 1
[2025-08-07 22:33:44,976] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-07 22:33:44,982] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=send_weather_to_kafka, task_id=run_py_spark_job, execution_date=20250807T203304, start_date=20250807T223344, end_date=20250807T223344
[2025-08-07 22:33:45,004] {standard_task_runner.py:97} ERROR - Failed to execute job 660 for task run_py_spark_job (Bash command failed. The command returned a non-zero exit code 1.; 5082)
[2025-08-07 22:33:45,027] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-08-07 22:33:45,099] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
