[2025-08-07 10:52:21,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-07T10:50:14.997141+00:00 [queued]>
[2025-08-07 10:52:21,063] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-07T10:50:14.997141+00:00 [queued]>
[2025-08-07 10:52:21,063] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 10:52:21,063] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-07 10:52:21,063] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 10:52:21,080] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): verify_pipeline> on 2025-08-07 10:50:14.997141+00:00
[2025-08-07 10:52:21,086] {standard_task_runner.py:52} INFO - Started process 6583 to run task
[2025-08-07 10:52:21,090] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'verify_pipeline', 'scheduled__2025-08-07T10:50:14.997141+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpabk31k1t', '--error-file', '/tmp/tmpvk7v3n0v']
[2025-08-07 10:52:21,092] {standard_task_runner.py:80} INFO - Job 129: Subtask verify_pipeline
[2025-08-07 10:52:21,167] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.verify_pipeline scheduled__2025-08-07T10:50:14.997141+00:00 [running]> on host 81d3b97a0728
[2025-08-07 10:52:21,443] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alla
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=verify_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2025-08-07T10:50:14.997141+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-07T10:50:14.997141+00:00
[2025-08-07 10:52:21,444] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-07 10:52:21,445] {subprocess.py:74} INFO - Running command: ['bash', '-c', '\n            echo " Attente traitement Logstash..." && sleep 30 &&\n            curl -s "http://elasticsearch:9200/_cat/indices/weather*" || echo "Pas encore d\'index weather"\n        ']
[2025-08-07 10:52:21,463] {subprocess.py:85} INFO - Output:
[2025-08-07 10:52:21,466] {subprocess.py:92} INFO -  Attente traitement Logstash...
[2025-08-07 10:52:51,491] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-07 10:52:51,544] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=verify_pipeline, execution_date=20250807T105014, start_date=20250807T105221, end_date=20250807T105251
[2025-08-07 10:52:51,579] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-08-07 10:52:51,583] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 6583. PIDs of all processes in the group: [6583]
[2025-08-07 10:52:51,583] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 6583
[2025-08-07 10:52:51,590] {process_utils.py:75} INFO - Process psutil.Process(pid=6583, status='terminated', exitcode=0, started='10:52:20') (6583) terminated with exit code 0
