[2025-08-07 03:29:48,172] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_trigger_target_dag.bash_task manual__2025-08-07T03:29:46.729496+00:00 [queued]>
[2025-08-07 03:29:48,189] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_trigger_target_dag.bash_task manual__2025-08-07T03:29:46.729496+00:00 [queued]>
[2025-08-07 03:29:48,189] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 03:29:48,189] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-08-07 03:29:48,190] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-07 03:29:48,221] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): bash_task> on 2025-08-07 03:29:46.729496+00:00
[2025-08-07 03:29:48,231] {standard_task_runner.py:52} INFO - Started process 304 to run task
[2025-08-07 03:29:48,251] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_trigger_target_dag', 'bash_task', 'manual__2025-08-07T03:29:46.729496+00:00', '--job-id', '7', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_trigger_target_dag.py', '--cfg-path', '/tmp/tmp55kcsd6c', '--error-file', '/tmp/tmpdjvnqpn2']
[2025-08-07 03:29:48,258] {standard_task_runner.py:80} INFO - Job 7: Subtask bash_task
[2025-08-07 03:29:48,493] {task_command.py:369} INFO - Running <TaskInstance: example_trigger_target_dag.bash_task manual__2025-08-07T03:29:46.729496+00:00 [running]> on host 47565329e35b
[2025-08-07 03:29:49,240] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_trigger_target_dag
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2025-08-07T03:29:46.729496+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-07T03:29:46.729496+00:00
[2025-08-07 03:29:49,242] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-07 03:29:49,243] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "Here is the message: $message"']
[2025-08-07 03:29:49,291] {subprocess.py:85} INFO - Output:
[2025-08-07 03:29:49,295] {subprocess.py:92} INFO - Here is the message: Hello World
[2025-08-07 03:29:49,297] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-07 03:29:49,710] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_trigger_target_dag, task_id=bash_task, execution_date=20250807T032946, start_date=20250807T032948, end_date=20250807T032949
[2025-08-07 03:29:49,829] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-07 03:29:50,048] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
