[2025-08-08 08:55:06,155] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_subdag_operator.section-1 scheduled__2025-08-06T00:00:00+00:00 [queued]>
[2025-08-08 08:55:06,271] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_subdag_operator.section-1 scheduled__2025-08-06T00:00:00+00:00 [queued]>
[2025-08-08 08:55:06,271] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-08 08:55:06,271] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2025-08-08 08:55:06,271] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-08 08:55:06,422] {taskinstance.py:1377} INFO - Executing <Task(SubDagOperator): section-1> on 2025-08-06 00:00:00+00:00
[2025-08-08 08:55:06,435] {standard_task_runner.py:52} INFO - Started process 347 to run task
[2025-08-08 08:55:06,453] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_subdag_operator', 'section-1', 'scheduled__2025-08-06T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_subdag_operator.py', '--cfg-path', '/tmp/tmp13oma3_t', '--error-file', '/tmp/tmp0yo9s3bw']
[2025-08-08 08:55:06,472] {standard_task_runner.py:80} INFO - Job 13: Subtask section-1
[2025-08-08 08:55:06,680] {task_command.py:369} INFO - Running <TaskInstance: example_subdag_operator.section-1 scheduled__2025-08-06T00:00:00+00:00 [running]> on host abdeb7f02efc
[2025-08-08 08:55:07,505] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_subdag_operator
AIRFLOW_CTX_TASK_ID=section-1
AIRFLOW_CTX_EXECUTION_DATE=2025-08-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-06T00:00:00+00:00
[2025-08-08 08:55:07,520] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-08-08 08:55:07,588] {subdag.py:176} INFO - Created DagRun: scheduled__2025-08-06T00:00:00+00:00
[2025-08-08 08:56:07,694] {base.py:301} INFO - Success criteria met. Exiting.
[2025-08-08 08:56:07,706] {subdag.py:191} INFO - Execution finished. State is success
[2025-08-08 08:56:07,723] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_subdag_operator, task_id=section-1, execution_date=20250806T000000, start_date=20250808T085506, end_date=20250808T085607
[2025-08-08 08:56:07,746] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-08-08 08:56:07,751] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 347. PIDs of all processes in the group: [347]
[2025-08-08 08:56:07,752] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 347
[2025-08-08 08:56:07,759] {process_utils.py:75} INFO - Process psutil.Process(pid=347, status='terminated', exitcode=0, started='08:55:06') (347) terminated with exit code 0
