[2025-08-08 08:58:48,289] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.run_py_spark_job scheduled__2025-08-08T06:55:01.093521+00:00 [queued]>
[2025-08-08 08:58:48,296] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.run_py_spark_job scheduled__2025-08-08T06:55:01.093521+00:00 [queued]>
[2025-08-08 08:58:48,296] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-08 08:58:48,296] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2025-08-08 08:58:48,296] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-08 08:58:48,311] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_py_spark_job> on 2025-08-08 06:55:01.093521+00:00
[2025-08-08 08:58:48,314] {standard_task_runner.py:52} INFO - Started process 2575 to run task
[2025-08-08 08:58:48,317] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'run_py_spark_job', 'scheduled__2025-08-08T06:55:01.093521+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmp8gigj1mz', '--error-file', '/tmp/tmph8w4bkfk']
[2025-08-08 08:58:48,318] {standard_task_runner.py:80} INFO - Job 76: Subtask run_py_spark_job
[2025-08-08 08:58:48,393] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.run_py_spark_job scheduled__2025-08-08T06:55:01.093521+00:00 [running]> on host abdeb7f02efc
[2025-08-08 08:58:48,577] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alla
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=run_py_spark_job
AIRFLOW_CTX_EXECUTION_DATE=2025-08-08T06:55:01.093521+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-08T06:55:01.093521+00:00
[2025-08-08 08:58:48,578] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-08 08:58:48,578] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && spark-submit py_spark/pyspark_streaming_meteo.py']
[2025-08-08 08:58:48,591] {subprocess.py:85} INFO - Output:
[2025-08-08 08:58:48,693] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-08-08 08:58:48,695] {subprocess.py:92} INFO - JAVA_HOME is not set
[2025-08-08 08:58:48,695] {subprocess.py:96} INFO - Command exited with return code 1
[2025-08-08 08:58:48,714] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-08 08:58:48,719] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=send_weather_to_kafka, task_id=run_py_spark_job, execution_date=20250808T065501, start_date=20250808T085848, end_date=20250808T085848
[2025-08-08 08:58:48,727] {standard_task_runner.py:97} ERROR - Failed to execute job 76 for task run_py_spark_job (Bash command failed. The command returned a non-zero exit code 1.; 2575)
[2025-08-08 08:58:48,769] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-08-08 08:58:48,816] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
