[2025-08-06 11:42:31,372] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-06T11:42:30.053593+00:00 [queued]>
[2025-08-06 11:42:31,389] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-06T11:42:30.053593+00:00 [queued]>
[2025-08-06 11:42:31,389] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 11:42:31,389] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-06 11:42:31,389] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 11:42:31,413] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-06 11:42:30.053593+00:00
[2025-08-06 11:42:31,418] {standard_task_runner.py:52} INFO - Started process 23110 to run task
[2025-08-06 11:42:31,421] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'manual__2025-08-06T11:42:30.053593+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmptrcgkn4c', '--error-file', '/tmp/tmp9z5_m3q3']
[2025-08-06 11:42:31,422] {standard_task_runner.py:80} INFO - Job 29: Subtask fetch_and_send_weather
[2025-08-06 11:42:31,485] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather manual__2025-08-06T11:42:30.053593+00:00 [running]> on host 536c12e0b7f9
[2025-08-06 11:42:31,596] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-06T11:42:30.053593+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-06T11:42:30.053593+00:00
[2025-08-06 11:42:31,598] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-06 11:42:31,599] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-06 11:42:31,617] {subprocess.py:85} INFO - Output:
[2025-08-06 11:42:36,281] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 30, 'humidity': 75, 'windSpeed': 3.1, 'cloudCover': 50, 'rainIntensity': 0, 'timestamp': '2025-08-06T11:42:00Z'}
[2025-08-06 11:42:36,336] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-06 11:42:36,380] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250806T114230, start_date=20250806T114231, end_date=20250806T114236
[2025-08-06 11:42:36,416] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-06 11:42:36,457] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
