[2025-08-06 20:31:08,421] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:30:47.765162+00:00 [queued]>
[2025-08-06 20:31:08,436] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:30:47.765162+00:00 [queued]>
[2025-08-06 20:31:08,437] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 20:31:08,437] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-06 20:31:08,437] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-06 20:31:08,453] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): fetch_and_send_weather> on 2025-08-06 18:30:47.765162+00:00
[2025-08-06 20:31:08,465] {standard_task_runner.py:52} INFO - Started process 3464 to run task
[2025-08-06 20:31:08,471] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'send_weather_to_kafka', 'fetch_and_send_weather', 'scheduled__2025-08-06T18:30:47.765162+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag_meteo.py', '--cfg-path', '/tmp/tmpm5fs2z16', '--error-file', '/tmp/tmpb9e9k2wx']
[2025-08-06 20:31:08,474] {standard_task_runner.py:80} INFO - Job 2: Subtask fetch_and_send_weather
[2025-08-06 20:31:08,599] {task_command.py:369} INFO - Running <TaskInstance: send_weather_to_kafka.fetch_and_send_weather scheduled__2025-08-06T18:30:47.765162+00:00 [running]> on host 614d63d93dd7
[2025-08-06 20:31:08,960] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=send_weather_to_kafka
AIRFLOW_CTX_TASK_ID=fetch_and_send_weather
AIRFLOW_CTX_EXECUTION_DATE=2025-08-06T18:30:47.765162+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-08-06T18:30:47.765162+00:00
[2025-08-06 20:31:08,962] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-08-06 20:31:08,963] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/scripts && python3 kafka/producer.py']
[2025-08-06 20:31:08,995] {subprocess.py:85} INFO - Output:
[2025-08-06 20:31:13,923] {subprocess.py:92} INFO - Envoi vers Kafka : {'temperature': 29, 'humidity': 79, 'windSpeed': 4.1, 'cloudCover': 100, 'rainIntensity': 0, 'timestamp': '2025-08-06T20:31:00Z'}
[2025-08-06 20:31:14,094] {subprocess.py:96} INFO - Command exited with return code 0
[2025-08-06 20:31:14,169] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=send_weather_to_kafka, task_id=fetch_and_send_weather, execution_date=20250806T183047, start_date=20250806T203108, end_date=20250806T203114
[2025-08-06 20:31:14,251] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-06 20:31:14,327] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
